### ISSUE TITLE
Support for date-fns@2?

### ISSUE THREAD

**Issue by dteirney** [date-fns/babel-plugin-date-fns#12]
Hello,

We rely on this babel plugin to help with bundling only application code that we use. Does it support the somewhat recent date-fns 2.x release?

Thanks!
David

**Comment by dteirney** [comment]
PR https://github.com/date-fns/babel-plugin-date-fns/pull/6 looks related. What's the likely versioning strategy for this babel plugin? Will there be a major version bump that supports date-fns@2 and this existing major version supports date-fns@1?

**Comment by existentialism** [comment]
@dteirney yeah, sorry for delay... been super busy. Plan is to land #6 for @2 support asap.

**Comment by Gzbox** [comment]
Waiting for upgrade

**Comment by existentialism** [comment]
Fixed in https://github.com/date-fns/babel-plugin-date-fns/commit/c479a38d0905b0de893929da79c3e09c1c5e2649
