### ISSUE TITLE
Programmatically generate import names?

### ISSUE THREAD

**Issue by developit** [date-fns/babel-plugin-date-fns#4]
Hi there - it seems like this is doing a module lookup right now to determine the import filename.  What about doing it programmatically, seeing as `date-fns`'s filenames follow a pattern:

```js
function importNameToFilename(importName) {
  return 'date-fns/' + importName.replace(/([A-Z])/, '_$1').toLowerCase();
}

importNameToFilename('startOfYear') // "date-fns/start_of_year"
importNameToFilename('differenceInCalendarDays') // "date-fns/difference_in_calendar_days"
```

It seems like this would address #2.

**Comment by kossnocorp** [comment]
Yup, the pattern is consistent, so we can totally do it! It's a sweet suggestion, thank you!

**Comment by existentialism** [comment]
Fixed in https://github.com/date-fns/babel-plugin-date-fns/pull/5
